pipeline {
  agent any
  options { timestamps() }

  environment {
    COMPOSE_FILE = "docker-compose.yml"
    DOCKER_CREDS_ID = "dockerhub-creds"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build TODAS las imagenes') {
      steps {
        bat """
@echo on
echo ===== BUILD DE TODAS LAS IMAGENES =====
docker compose -f %COMPOSE_FILE% build
IF %ERRORLEVEL% NEQ 0 EXIT /B 1
"""
      }
    }

    stage('Login Docker Hub') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: DOCKER_CREDS_ID,
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          bat """
@echo on
echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
IF %ERRORLEVEL% NEQ 0 EXIT /B 1
"""
        }
      }
    }

    stage('Push TODAS las imagenes') {
      steps {
        bat """
@echo on
echo ===== PUSH DE TODAS LAS IMAGENES =====
docker compose -f %COMPOSE_FILE% push
IF %ERRORLEVEL% NEQ 0 EXIT /B 1
"""
      }
    }
  }

  post {
    always {
      bat """
@echo on
echo ===== FIN DEL PIPELINE =====
docker logout
"""
    }
  }
}




